name: Build and Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
    - main

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        check-latest: true

    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        run_install: false

    - name: Get pnpm store directory
      id: get-store-path
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> "$GITHUB_OUTPUT"

    - uses: actions/cache@v4
      name: Setup pnpm cache
      with:
        path: ${{ steps.get-store-path.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - uses: oven-sh/setup-bun@v2

    - name: Install dependencies
      run: pnpm install --no-frozen-lockfile

    - name: lint
      env:
        CI: true
      run: bun run lint

    - name: build
      env:
        CI: true
      run: bun run build
